#!/bin/bash
set_timezone() {
  if [ $TZ ]; then
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
  fi
}

create_group_user() {
  if [ ! $UID ] || [ ! $GID ] || id -u $UID >/dev/null 2>&1 || getent group $GID >/dev/null 2>&1; then
    USER=$(getent passwd "$UID" | cut -d: -f1)
    return 0
  fi

  if ! grep -q ":$GID:" /etc/group; then
    groupadd -g "$GID" steam
  fi

  if ! id "$UID" &>/dev/null; then
    useradd -u "$UID" -g "$GID" -m steam
  fi

  USER=$(getent passwd "$UID" | cut -d: -f1)
}

create_directory() {
  mkdir -p $STEAM_DIRECTORY $ZOMBOID_DIRECTORY $DATA_DIRECTORY /home/$USER
  ln -s $DATA_DIRECTORY /home/$USER/Zomboid
}

download_steamcmd() {
  cd $STEAM_DIRECTORY
  curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
}

download_zomboid() {
  echo -e "@ShutdownOnFailedCommand 1\n@NoPromptForPassword 1\nforce_install_dir $ZOMBOID_DIRECTORY/\nlogin anonymous\napp_update 380870 validate\nquit" >$STEAM_DIRECTORY/zomboid.txt
  $STEAM_DIRECTORY/steamcmd.sh +runscript $STEAM_DIRECTORY/zomboid.txt
  cat $ZOMBOID_DIRECTORY/ProjectZomboid64.json | jq --arg ram "-Xmx$RAM" '.vmArgs[1] |= $ram' > ./tmp.json
  mv ./tmp.json $ZOMBOID_DIRECTORY/ProjectZomboid64.json
}

set_chown() {
  chown -R $USER /home/$USER $STEAM_DIRECTORY $ZOMBOID_DIRECTORY $DATA_DIRECTORY
}

run_server() {
  sudo -u $USER $ZOMBOID_DIRECTORY/start-server.sh -servername $SERVER_NAME -adminusername $ADMIN_USERNAME -adminpassword $ADMIN_PASSWORD
}

set_timezone
create_group_user
create_directory
download_steamcmd
download_zomboid
set_chown
run_server
